apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ylz-iam-svc
  name: ylz-iam-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ylz-iam-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ylz-iam-svc
    spec:
      containers:
        - name: ylz-iam-svc
          image: gcr.io/ylz-infra/github.com/aytekinyaliz/ylz-iam-svc
          imagePullPolicy: IfNotPresent
          env:
            - name: API_PREFIX
              valueFrom:
                configMapKeyRef:
                  key: API_PREFIX
                  name: ylz-iam-svc-config-e8aq
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: ylz-iam-svc-config-e8aq
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: ylz-iam-svc-config-e8aq
